name: Tests

on:
  pull_request:
  push:
    branches: [master, main]

jobs:
  linux-tests:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-image-tags }}
    strategy:
      matrix:
        # When making chances here remember to update the tag also in line 34!
        qgis-image-tags: [release-3_22, release-3_34, "3.44"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: |
          apt update
          apt install -y python3-venv
      - run: |
          python3 -m venv --system-site-packages .venv
      - run: |
          .venv/bin/pip3 install -q -U uv
          .venv/bin/uv sync --all-packages --all-groups --locked --active
      - run: |
          .venv/bin/uv run pytest -v --cov=pickLayer --cov-report=xml test
        env:
          QT_QPA_PLATFORM: offscreen
      # Upload coverage report. Will not work if the repo is private
      # Rememeber to check that tag specified below can be found in the matrix created at line 16!
      - if: ${{ matrix.qgis_image_tags == '3.44' && !github.event.repository.private }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: false
        env:
          QT_QPA_PLATFORM: offscreen

  windows_tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install qgis-ltr -y
      - shell: pwsh
        run: |
          $env:QGIS_PATH = (Get-ChildItem "C:\Program Files\QGIS *\bin" | Select-Object -First 1 -ExpandProperty FullName)
          $env:PATH="$env:QGIS_PATH;$env:PATH"
          $env:QGIS_PLUGIN_IN_CI=1
          python-qgis-ltr.bat -m pip install -q -U uv
          python-qgis-ltr.bat -m pip install -q -U uv
          python-qgis-ltr.bat -m pytest -v test

  plugin_zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install Python 3.12
        run: uv python install 3.12
      # Cannot be editable install
      # so that .dist-info will go the package instead of .egg-info
      - run: |
          uv sync --no-editable --only-dev
      - run: |
          qgis-plugin-dev-tools build
      - uses: actions/upload-artifact@v7
        with:
          name: plugin-zip
          path: dist/*.zip
